<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WorkOrders.aspx.cs" Inherits="BronzeWebUtils.WorkOrders" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            width: 238px;
        }
        .style3
        {
            width: 235px;
        }
        .style4
        {
            width: 151px;
        }
        .style5
        {
            width: 204px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <table class="style1">
            <tr>
                <td>
                    Select Engineer</td>
                <td class="style2">
                    Select Start Date</td>
                <td class="style3">
                    Select End Date</td>
                <td class="style4">
                    Job Number
                    <br />
                    (blank All)</td>
                <td class="style5">
                    Unit Number<br />
                    (blank All)</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td>
                    <asp:DropDownList ID="ddlEng" runat="server" DataTextField="Name" DataValueField="Name" >
                    </asp:DropDownList>
                </td>
                <td class="style2">
                    <asp:Calendar ID="calStart" runat="server" BackColor="White" 
                        BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" 
                        DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" 
                        ForeColor="#003399" Height="200px" Width="220px">
                        <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                        <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                        <OtherMonthDayStyle ForeColor="#999999" />
                        <SelectedDayStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                        <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                        <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" 
                            Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                        <TodayDayStyle BackColor="#99CCCC" ForeColor="White" />
                        <WeekendDayStyle BackColor="#CCCCFF" />
                    </asp:Calendar>
                </td>
                <td class="style3">
                    <asp:Calendar ID="calEnd" runat="server" BackColor="White" 
                        BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" 
                        DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" 
                        ForeColor="#003399" Height="200px" Width="220px">
                        <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                        <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                        <OtherMonthDayStyle ForeColor="#999999" />
                        <SelectedDayStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                        <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                        <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" 
                            Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                        <TodayDayStyle BackColor="#99CCCC" ForeColor="White" />
                        <WeekendDayStyle BackColor="#CCCCFF" />
                    </asp:Calendar>
                </td>
                <td class="style4">
                    <asp:TextBox ID="txtJobID" runat="server"></asp:TextBox>
                </td>
                <td class="style5">
                    <asp:TextBox ID="txtDisplayID" runat="server"></asp:TextBox>
                </td>
                <td>
                    <asp:Button ID="btnGo" runat="server" onclick="btnGo_Click" Text="go" />
                </td>
            </tr>
        </table>
        <br />
        <asp:Label ID="Label1" runat="server" Text="Bronze"></asp:Label>
        <br />
    
        <asp:GridView ID="gvOrders" runat="server" AutoGenerateDeleteButton="True" 
            onrowdeleting="gvOrders_RowDeleting" AutoGenerateSelectButton="True" 
            onrowcommand="gvOrders_RowCommand">
        </asp:GridView>
    
        <br />
    
        <br />
        <asp:Button ID="btnHome" runat="server" onclick="btnHome_Click" Text="Home" />
    
    </div>
    </form>
</body>
</html>
